### ISSUE TITLE
RSS feeds can't be deleted

### ISSUE THREAD

**Issue by whalehub** [CzBiX/qb-web#10]
If you try to delete an RSS feed with this UI turned on, you get an error message saying "Item doesn't exist: <RSS feed URL>" (screenshots below). I'm running qb-web commit 2f5bd38.

![2020-03-31 08 41 10 qbittorrent datahoarder dev 19acacd7b3e9](https://user-images.githubusercontent.com/44198148/77995235-b410a880-732b-11ea-9ebb-bc3f050995b0.png)

![2020-03-31 08 41 18 qbittorrent datahoarder dev a8b022d8b92f](https://user-images.githubusercontent.com/44198148/77995246-b7a42f80-732b-11ea-8368-e6976a4dfdeb.png)

![2020-03-31 08 41 23 qbittorrent datahoarder dev 571b46f41907](https://user-images.githubusercontent.com/44198148/77995252-b96df300-732b-11ea-8b93-65b54799c48d.png)

![vivaldi_2020-03-31_08-41-46](https://user-images.githubusercontent.com/44198148/77995665-8d06a680-732c-11ea-960a-41b13b27cad3.png)

**Comment by CzBiX** [comment]
QB version?

**Comment by whalehub** [comment]
I'm running qBittorrent v4.2.2.

**Comment by whalehub** [comment]
I'm using qBittorrent v4.2.2.

**Comment by whalehub** [comment]
@CzBiX
