### ISSUE TITLE
dsm7 4.3.6  设置后出现错误：不可接受的文件类型，只允许使用常规文件

### ISSUE THREAD

**Issue by realyn** [CzBiX/qb-web#111]
文件夹权限设置everyone 可读写，qbittorrent 可读写

文件路径：/volume1/Toolz/qBittorrent/CzBiX/

（dist实际路径为：/volume1/Toolz/qBittorrent/CzBiX/dist）

应用后报错：不可接受的文件类型，只允许使用常规文件

**Comment by CzBiX** [comment]
#3, #98
