### ISSUE TITLE
手机版webui找不到rss功能

### ISSUE THREAD

**Issue by grassjelly-ryan** [CzBiX/qb-web#113]
请问这是bug还是没有开发呢？
如果没有开发，希望后续能支持一下，谢谢～
![C8C086C6-5979-4DA8-8339-275CFE98FEA6](https://user-images.githubusercontent.com/53893277/133932397-074f6ec7-f98c-4b80-964e-f932c2e2ce03.jpeg)

**Comment by CzBiX** [comment]
RSS界面没有为手机考虑，在手机上屏蔽了这个功能。请用电脑访问。
