### ISSUE TITLE
[Help]Language selection of mobile version...

### ISSUE THREAD

**Issue by Goooooooooood** [CzBiX/qb-web#115]
It would be great if the author could provide language selection on the mobile version of the web page.
Thanks.

在iOS 14 Safari上，我遇到了这个问题：不能正确自动设置UI的语言、无法手动选择语言、试图“请求桌面网站”来切换语言也不行。

如果作者能在移动版网页提供语言选择，那将是极好。
谢谢。

**Comment by CzBiX** [comment]
duplicated #100
