### ISSUE TITLE
[Feature Request] Add option to specify the location that files should be downloaded to

### ISSUE THREAD

**Issue by whalehub** [CzBiX/qb-web#12]
I'm running qb-web eec497a on qBittorrent v4.2.2 and when I press the button to add a torrent, a window pops up with most options that are present in the official UI.

![vivaldi_2020-04-01_16-27-19](https://user-images.githubusercontent.com/44198148/78149802-b3186d80-7436-11ea-94f0-003c9f12c4d0.png)

An important option that's missing right now is the option to specify the location that a torrent's files should be downloaded to.

![vivaldi_2020-04-01_16-32-08](https://user-images.githubusercontent.com/44198148/78149853-c3c8e380-7436-11ea-9eb9-3225b4c12ee3.png)

It would be good if this option could be added to the "Add Torrents" window in qb-web.

**Comment by CzBiX** [comment]
If you only use fixed paths, like `/Movies/`, `/Books/`, these are a workaround right now.
You can set the path of category, then select it in the form.

**Comment by whalehub** [comment]
@CzBiX That doesn't seem to work for me. I set the path of the "movies" category to /downloads/movies and selected that category when adding a torrent, but the files were still saved to /downloads and remained there even once the torrent had finished downloading.

**Comment by CzBiX** [comment]
You may have to set "Torrent Management Mode" to "Automatic" in QB settings.

![image](https://user-images.githubusercontent.com/760097/78207731-1b1d9100-74d5-11ea-92e0-2dcc1a394ed4.png)

**Comment by whalehub** [comment]
@CzBiX It works with that option turned on - thank you!
