### ISSUE TITLE
Firefox: Blocked loading mixed active content 

### ISSUE THREAD

**Issue by azumukupoe** [CzBiX/qb-web#121]
## Describe the bug

can't load the page due to mixed content blocking in Firefox

## How to reproduce

1. open Firefox
2. go to https://czbix.github.io/qb-web/
3. F12
4. Blocked loading mixed active content “qb url here”

## Expected behavior

_description of what you expected to happen._

## Official behavior

_description of what happened in the official web ui._

## Versions

- qBittorrent: 4.3.9 
- qb-web: [e.g. 20201023]

## Additional notes

as a workaround, you can disable blocking for czbix.github.io
https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox

**Comment by CzBiX** [comment]
It's expected. You need https to use the online version.
Also, the online version has other problems, please use the local version.
