### ISSUE TITLE
[BUG]Request failed with status code 415

### ISSUE THREAD

**Issue by wendaleruan** [CzBiX/qb-web#129]
## Describe the bug
添加上传位于文件中种子，提交的时候显示：Request failed with status code 415

使用设备：iphone 13
手机浏览器：chrome 101

电脑浏览器上是没有问题的

## Versions

- qBittorrent: 4.4.2
- qb-web: 20220409

**Comment by CzBiX** [comment]
415 是种子文件有问题，请核查
