### ISSUE TITLE
Unacceptable file type, only regular file is allowed.

### ISSUE THREAD

**Issue by dextouu** [CzBiX/qb-web#13]
Hi, I wanted this alternative version of webui to access the rss function.
As soon as I apply the webui, I get this error message "Unacceptable file type, only regular file is allowed."
There aren't many posts on the web that talk about this error and how to fix it.
My version of qbitorrent-nox is 4.2.2.

**Comment by CzBiX** [comment]
Check your WebUI path settings and file permissions again.

**Comment by Sparh4wk** [comment]
Hi, I have the same problem with 20200720-192413 version.
Im using qbitorrent docker from linuxserver.. I tested few webuis.. all worked, but Im getting the same error with yours webui..
I think its the best webui I saw, but for some reason I cant run it :(
any idea? I checked permissions and settings..

**Comment by Sparh4wk** [comment]
> 
> 
> Check your WebUI path settings and file permissions again.

Hi, I have the same problem with 20200720-192413 version.
Im using qbitorrent docker from linuxserver.. I tested few webuis.. all worked, but Im getting the same error with yours webui..
I think its the best webui I saw, but for some reason I cant run it :(
any idea? I checked permissions and settings..

**Comment by YunhaoJiang** [comment]
Same issue here

**Comment by leni8ec** [comment]
> Im using qbitorrent docker from linuxserver..

Same here..
