### ISSUE TITLE
提几个小建议哈

### ISSUE THREAD

**Issue by lee911214** [CzBiX/qb-web#131]
首先，对大佬开发这个webui表示辛苦了，做的挺好的，界面等功能。不过容许我提几个小建议哈，希望大佬能够采纳~
①种子列表当中能否添加“已下载”和“已上传”这两项数据，因为很多人用盒子或家宽都想看看该种子刷了多少，虽然有个比率，但是并不能完全看出具体上传了多少~   或者像原版webui一样提供右键自行决定显示哪些
②能否提供下载上传的速度曲线图？为了美观，高大上。哈哈哈。这个可能工程量比较大，添加不了无所谓
③能否下下方栏（显示硬盘容量，速度，种子大小那里）添加个“队列的 I/O 任务”和“在队列的平均时间”，因为用qb下载过快没上传时候可能会出现卡io的现象，如果单纯的从速度来看完全判断不出来硬盘是否卡了，所以需要这两项来判断。如两项不能都显示，显示“队列的 I/O 任务”即可

总结下，就是希望大佬能够满足①和②两项，③尽量满足。  

最后感谢大佬的辛苦制作和付出

**Comment by lee911214** [comment]
还有个，能否像原版在标题栏显示当前速度？

**Comment by lee911214** [comment]
还有能否增加右键属性啊？添加种子时候能否增加限制速度选项？想给种子限速都不行，只能去原版

**Comment by CzBiX** [comment]
请分开创建 issue。
