### ISSUE TITLE
[Feature Request] Add option to filter torrents by tag

### ISSUE THREAD

**Issue by whalehub** [CzBiX/qb-web#14]
This functionality exists in the original UI, but I can't find it in qb-web. I'm running qb-web fe3cc3a with qBittorrent v4.2.2.

![vivaldi_2020-04-03_14-47-01](https://user-images.githubusercontent.com/44198148/78362191-fbac6400-75b9-11ea-99bf-f4ea5204f50d.png)

![vivaldi_2020-04-03_14-47-30](https://user-images.githubusercontent.com/44198148/78362250-14b51500-75ba-11ea-9694-803860ec64f5.png)

**Comment by CzBiX** [comment]
fixed in #145.
