### ISSUE TITLE
[BUG] Locale issue in Settings > Web UI > Authentication

### ISSUE THREAD

**Issue by Blacktea0** [CzBiX/qb-web#142]
Both options in settings has same description.

![image](https://user-images.githubusercontent.com/13018564/179547177-92020ef6-ff23-4fcf-938e-2ac1007eeb69.png)

https://github.com/CzBiX/qb-web/blob/8e21873afa8a0a73132348c6ab4f7f5c3f6221df/src/locale/en.ts#L127

This line should be `Bypass authentication for clients in whitelisted IP subnets`.

**Comment by ripdog** [comment]
Opened a PR for you.

**Comment by CzBiX** [comment]
Fixed in #143
