### ISSUE TITLE
[BUG] Storage Size Display Different from Official Web UI

### ISSUE THREAD

**Issue by Blacktea0** [CzBiX/qb-web#147]
## Describe the bug

![image](https://user-images.githubusercontent.com/13018564/194382137-9508aff4-4203-4cee-b0bc-cee4f46c30c4.png)

File size displayed in second and third rows different from official version, and it should not display in scientific notation like '1e3'.

## How to reproduce

1.  Create torrent with file size 1,048,401,181 bytes
2.  Go to "Transfers" page
4.  See error

## Expected behavior

It should be same as official.

## Official behavior

![image](https://user-images.githubusercontent.com/13018564/194382250-5e4fd702-bd2c-439f-86b5-27b6f613eacd.png)

## Versions

- qBittorrent Enhanced Edition v4.4.5.10 Web UI
- qb-web: latest 79e515a3efc4f6dff6c1c0d61b3bbda76fa29953

## Additional notes

Maybe file size should round with floor here.

https://github.com/CzBiX/qb-web/blob/79e515a3efc4f6dff6c1c0d61b3bbda76fa29953/src/filters.ts#L5-L30

**Comment by CzBiX** [comment]
Thanks, fixed.
