### ISSUE TITLE
任务列表未显示,Console有报错

### ISSUE THREAD

**Issue by DreamL** [CzBiX/qb-web#151]
运行情况
服务器统计信息正常显示、可正常添加任务、几乎可以说除了任务列表外都工作正常

问题现状
任务列表无数据显示

重现步骤
直接打开本UI即可重现

相关信息:
qBittorrent: 4.1.7
webapiVersion: 2.2
OS: Windows11 22H2 22638
browser: Chrome108.0.5359.125 64位
sync/maindata、app/version、app/preferences、app/webapiVersion、sync/maindata?rid=1等请求都正常返回了看上去有效的数据
其中maindata请求数据格式如下:
![image](https://user-images.githubusercontent.com/8446543/211320675-5868a460-1637-49b1-b664-ddbe52acc28b.png)

console有一处报错顶层堆栈如下:
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at r (createForOfIteratorHelper.js:3:45)

全景图如下:
![image](https://user-images.githubusercontent.com/8446543/211321176-ac4175f6-4212-4dc3-9a28-19d8098cc2aa.png)

希望作者大佬能帮忙看一下是什么问题, 感谢!

**Comment by CzBiX** [comment]
应该是QB版本太低，不支持tags功能导致的报错。可以升级QB到4.2.0以上版本看看

**Comment by DreamL** [comment]
> 

由于一些限制，我无法升级QB，比较遗憾，只能切回原版UI了。
