### ISSUE TITLE
[BUG]多标签种子仅能匹配到第一个标签

### ISSUE THREAD

**Issue by NicholasYZ** [CzBiX/qb-web#158]
## 问题描述

标签筛选仅显示第一个标签

## 期望行为

标签列表中能显示所有包含该标签的种子，而非仅仅是第一个标签为该标签的种子

## 官方webui行为

多标签种子在各标签中均能正常显示

## Versions

- qBittorrent: 4.2.5
- qb-web: [nightly-20230423](https://github.com/CzBiX/qb-web/releases/tag/nightly-20230423)

## Additional notes

qbit的标签与分类不同，不具备排他性，故此我猜测可能是在实现标签筛选时使用了和分类相同的逻辑，而多标签在某些场景（尤其是需要统计tracker做种体积的场景）中也时常用到，恳请修复。
另外，如果方便实现的话，或许可以考虑多选标签以筛选种子，目前似乎尚不存在有webui实现了这一功能。

**Comment by CzBiX** [comment]
多选标签的功能可以另外开一个 issue

**Comment by NicholasYZ** [comment]
等这个bug修复了之后~~而且我还没忘的时候~~，会再开一个enhancement的 ：)
