### ISSUE TITLE
恢复原版UI时提示Method Not Allowed

### ISSUE THREAD

**Issue by zycn0910** [CzBiX/qb-web#160]
![image](https://github.com/CzBiX/qb-web/assets/46790182/3ac2fdc9-5702-4135-820e-254b66f7c715)

**Comment by miuim** [comment]
新版本 qBittorrent 不能使用 GET修改配置了，改用 POST 就可以了
或者直接进入 SSH 修改配置文件 qBittorrent.conf （需要重启）

**Comment by wiiii** [comment]
按F12打开控制台，选择Console,输入请求接口：
fetch(new Request('url/api/v2/app/setPreferences',{
    method:'POST', 
    headers: {'Content-Type': 'application/x-www-form-urlencoded'},
    body:"json=%7B%22alternative_webui_enabled%22:false%7D"
})).then((resp)=>{console.log(resp)})

url 为你的qb的地址.

**Comment by wiiii** [comment]
4.5.5切换回原版切换不了

**Comment by caliban511** [comment]
所以在手机上要怎么方便的操作呢？

**Comment by caliban511** [comment]
> 所以在手机上要怎么方便的操作呢？

算了，ssh进去删了参数，，，还是用APP吧，，，😂😂😂
