### ISSUE TITLE
[BUG] Please avoid using Service Worker

### ISSUE THREAD

**Issue by stkevintan** [CzBiX/qb-web#167]
## Describe the bug

_description of what the bug is, and the conditions when it occurs._

## How to reproduce

Service worker will hugely prevent us switching webui.
As a web developer, Fortunately, I know the concept and I can disable it by myself.

but how about non-developers ? or the mobile system? 

As I experenced, I cannot get rid of the stale serviceworker cache in my ios browser, even I clean up all the browser history and cache

Even though I am a web developer, It still takes me nearly one day to find out **why the webui doesn't change when I disable or switch the alternative webui** 

I feel excited with the project but feel frustrated about the service worker, I believe many people faced the same issue but they cannot find the root cause, even after totally reinstall the qbittorrent at the cost of all the data lost
 

## Expected behavior
webui is just a small, simple , static site, it is totally enough to rely on the browser to cache resources.
Please consider to remove the ServiceWorker or make can be self unregistered somehow.

Thanks!

_description of what you expected to happen._

## Official behavior

_description of what happened in the official web ui._

## Versions

- qBittorrent: [e.g. 4.2.5]
- qb-web: [e.g. 20201023]

## Additional notes

_Add any other notes about the problem here._

**Comment by stkevintan** [comment]
Why someone don't encounter such issue?
I guess maybe they host their qbittorrent in ther localhost. so the serviceworker won't take effect.

**Comment by CzBiX** [comment]
Fixed in #168, thanks.
