### ISSUE TITLE
[Feature Request] Add search with search engines

### ISSUE THREAD

**Issue by Ingvix** [CzBiX/qb-web#19]
I usually add torrents via the qBittorrents search so currently I have to go back to default UI to do that. I hope you could implement it in your UI.

**Comment by bacon-cheeseburger** [comment]
I found this new webui looking for a RSS option but need the search option too. Hopefully the dev will implement this.

**Comment by jmaris** [comment]
I must admit this would be a really nice feature, it is the only reason i'm not using this webui alone

**Comment by CzBiX** [comment]
#46
