### ISSUE TITLE
Cannot apply to latest git master qbittorrent

### ISSUE THREAD

**Issue by caoli5288** [CzBiX/qb-web#2]
![图片](https://user-images.githubusercontent.com/3120587/64068296-c5e07f00-cc68-11e9-88e1-a46fec32ad96.png)

Will got empty page if apply your themes.

**Comment by CzBiX** [comment]
Try to clean the cache.

**Comment by caoli5288** [comment]
是正确的，之前用过别的ui，不会犯这种错误

**Comment by caoli5288** [comment]
![图片](https://user-images.githubusercontent.com/3120587/64075178-8c9b2400-cce7-11e9-878d-ac4370cb4d4a.png)
![图片](https://user-images.githubusercontent.com/3120587/64075187-a9cff280-cce7-11e9-8847-9da4fe5d8265.png)
![图片](https://user-images.githubusercontent.com/3120587/64075194-bd7b5900-cce7-11e9-964b-5718101bee05.png)

路径是绝对没问题的

**Comment by CzBiX** [comment]
我在 v4.2.0 alpha1 上测试可以正常使用。

如果因为路径或权限错误，应该会显示报错页（左上角有内容）而不是空白页。
注意设置成英文以免报错内容乱码。

**Comment by caoli5288** [comment]
@CzBix 就是空白的，另外，我按官方wiki上的复制源码树中的部分文件，或者只单独放你的release文件，都是一样的效果，

清缓存也尝试过，浏览器也试过了从firefox到chrome，好迷

**Comment by CzBiX** [comment]
试试只在 public 放一个 index.html，注意不要有 private 文件夹。然后随便写点内容，看能不能正常访问到。

**Comment by caoli5288** [comment]
@CzBiX 测了可以的

**Comment by caoli5288** [comment]
![图片](https://user-images.githubusercontent.com/3120587/64233946-db370100-cf27-11e9-9904-71acda92fbe9.png)
控制台有这些输出，抱歉才想起看下控制台

**Comment by CzBiX** [comment]
手动访问这些 URL 看返回的内容是什么。

**Comment by caoli5288** [comment]
@CzBiX 手动访问也是各种阻止信息

![图片](https://user-images.githubusercontent.com/3120587/64253893-d63a7780-cf50-11e9-8b46-ef6b4a7be38d.png)

**Comment by caoli5288** [comment]
额，好像哪里不对，我的qbittorrent是走反代的，abc.com/qbittorrent这样，这里的资源url好像都错了
