### ISSUE TITLE
[特性请求]RSS下载器增加下载目录选择

### ISSUE THREAD

**Issue by caoli5288** [CzBiX/qb-web#22]
例如通过rss下载剧集，希望将剧集自动下载到`/downloads/tvs/<剧集名>`而非默认的`/downloads`。请考虑添加这个功能，谢谢。

**Comment by CzBiX** [comment]
参考 https://github.com/CzBiX/qb-web/issues/12#issuecomment-607356924

**Comment by caoli5288** [comment]
@CzBiX 因为RSS也没有强制子目录的功能，如果需要借助分类来实现的话，就需要给每一个剧集创建一个分类，似乎违背了分类这个功能应有的粒度，也不便于管理种子。可否考虑直接添加路径功能呢？
