### ISSUE TITLE
Web page only loads blank white page

### ISSUE THREAD

**Issue by sevin8nin** [CzBiX/qb-web#24]
Running qBittorrent in Docker Container on Synology.
Enable custom WebUI and point to path for qb-web files, restart, only presents white screen. 
"View Page Source" shows that it has loaded the qb-web index.html, but nothing presents.

**Comment by CzBiX** [comment]
Post your Console output.

**Comment by bacon-cheeseburger** [comment]
I just found this webui looking for a RSS solution to qbittorrent-nox webui. I only get a white screen also.

**Comment by sevin8nin** [comment]
My Web Console is also blank when I look at it. The 'network' view shows a successful GET request (200) for "/" followed by a server 500 error while requesting:
`http://192.168.1.15:8080/%3C%=%20BASE_URL%20%%3Efavicon.ico`

**Comment by CzBiX** [comment]
@sevin8nin Use pre-compiled files in [releases](https://github.com/CzBiX/qb-web/releases/latest), not the repo itself.
