### ISSUE TITLE
[特性请求]添加手动修改rss订阅名的功能

### ISSUE THREAD

**Issue by caoli5288** [CzBiX/qb-web#28]
有时候自动出来的rss订阅名是错误的，请看截图。
![图片](https://user-images.githubusercontent.com/3120587/80196507-18cfd200-8650-11ea-9bba-94553cdee6d6.png)

以及因为默认是取url标题，会出现标题相同无法分辨的情况，需要可以手动修改订阅名。

**Comment by CzBiX** [comment]
没明白你说的“订阅名是错误的”是什么意思。
如果是说显示为 URL，那是因为还没有抓取到标题。

**Comment by caoli5288** [comment]
对，没抓去到标题，但是一直就那样了，不会自动变好。

而且不能自定义名字很不方便，比如两个rss都是同一个域名下的不同路径，服务器上没做处理标题相同，就很难办
