### ISSUE TITLE
不可接受的文件类型, 只允许使用常规文件。

### ISSUE THREAD

**Issue by piaoyun** [CzBiX/qb-web#3]
使用后这样提示：不可接受的文件类型, 只允许使用常规文件。

QB版本：4.1.7.1  
linux系统下的，请问下要怎么解决呢

**Comment by CzBiX** [comment]
请重新检查下路径设置和文件权限。

**Comment by oOTnTOo** [comment]
> 请重新检查下路径设置和文件权限。

请问linux下是不是只需要读写权限即可？路径需要后面的斜杠吗？

**Comment by CzBiX** [comment]
> 请问linux下是不是只需要读写权限即可？路径需要后面的斜杠吗？

文件夹需要 `r-x`，文件只需要 `r--`。
路径不需要斜杠。
