### ISSUE TITLE
Inconsistencies & weirdness in light and dark themes

### ISSUE THREAD

**Issue by bacon-cheeseburger** [CzBiX/qb-web#32]
There are a few strange things I've noticed with light/dark mode...

Light theme:
![webui-light](https://user-images.githubusercontent.com/10761393/81019634-eb3b1380-8e1b-11ea-8248-0596eda94336.jpg)

Dark theme:
![webui-dark](https://user-images.githubusercontent.com/10761393/81019718-1291e080-8e1c-11ea-9aee-3896f0beb72c.jpg)

**Comment by CzBiX** [comment]
When progress greater than 50%, it will show as white color (in light theme).

**Comment by bacon-cheeseburger** [comment]
Honestly, I think there's too much going on with the progress bars. I don't think the text color needs to change based on finished %. The text already tells me exactly how much is finished, changing the color doesn't help or add anything. And then only doing this light mode makes it inconsistent with dark mode where it should always be white. Please consider just making the % text only white in both modes!

Even changing the color of the progress bar isn't really necessary, there's a label next to it that tells the status (downloading/uploading/paused). There's also upload and download speed columns so there's plenty of indicators to know what's going on..

**Comment by CzBiX** [comment]
This color is not meant to indicate the status of the download progress.
When progress less than 50%, the progress value in white color is not obvious on a gray background, so I set it to black.

The different progress colors are used to quickly find active items in the list.

And yes, closed issue will also receive notifications.

**Comment by bacon-cheeseburger** [comment]
> 
> 
> This text color is not meant to indicate the status of the download progress.
> When progress less than 50%, the progress value in white color is not obvious on a gray background, so I set it to black.

I think this is a case of solving a non-existent problem. I can see the logic in the progress bar color but I don't see any advantage to changing the % text color at >=50%. There's nothing special about 50% and it breaks consistency with dark mode behavior. I guess we just have to agree to disagree on this one, which is ok.
