### ISSUE TITLE
批量更换tracker卡死

### ISSUE THREAD

**Issue by Ginnam** [CzBiX/qb-web#38]
如图将http://更换为https://，搜索到7个种子，然后一直转圈。https://i.endpot.com/image/ESDMD/%E5%8D%A1%E6%AD%BB.PNG
顺便一提，这个界面不错，希望继续坚持！

**Comment by Ginnam** [comment]
会不会是因为，更新后的tracker也连接不上，所以一直卡死？

**Comment by CzBiX** [comment]
按 F12 看看控制台有没有报错

**Comment by Ginnam** [comment]
![image](https://user-images.githubusercontent.com/51623730/102759178-bb427f80-43ae-11eb-836e-a88629845606.png)

**Comment by Ginnam** [comment]
![image](https://user-images.githubusercontent.com/51623730/102760083-f7c2ab00-43af-11eb-942f-f217d6585540.png)

**Comment by Ginnam** [comment]
[https://i.endpot.com/image/A0ZAT/%E6%8D%95%E8%8E%B7.PNG
](url)
现在还能回复吗qaq
