### ISSUE TITLE
手机ui不能下拉选择文件夹

### ISSUE THREAD

**Issue by molezz** [CzBiX/qb-web#42]
只能逐个输入

**Comment by CzBiX** [comment]
没明白你的意思。

**Comment by molezz** [comment]
嗯，就是添加种子以后， 下载路径那里只能填写或者默认， 没有选择历史路径的下拉项

**Comment by molezz** [comment]
![image](https://user-images.githubusercontent.com/695412/88242761-c9d22100-ccc0-11ea-8294-612578ccbafa.png)

**Comment by CzBiX** [comment]
使用种子自动管理+分类功能
