### ISSUE TITLE
Sidebar should not be in focus at launch

### ISSUE THREAD

**Issue by agneevX** [CzBiX/qb-web#48]
This behavior has always bugged me; why is the sidebar expanded, and in focus when the site is launched?

**Comment by bbogdanov** [comment]
Hi @agneevX! 

The change you are referring to sounds to be quickly fixable, so I would encourage you to do a PR with the change you would like to see.

**Comment by agneevX** [comment]
I wish! My coding skills are terrible ha ha! But thanks for asking.
