### ISSUE TITLE
使用CDN代替从本地拉取资源

### ISSUE THREAD

**Issue by mnixry** [CzBiX/qb-web#49]
目前本项目所采用的资源(如iconfont)都是直接在项目目录中放置
但是事实上有些情况下我们可能不具有流畅的网络来连接到远程服务器
所以是否应该考虑把资源URL指向某个CDN来代替指向本地资源?

**Comment by CzBiX** [comment]
我计划在之后的版本中，把项目修改成可离线使用的 PWA，就能解决你说的问题了。

---

I'm planning to make project as PWA site that can be used offline.

**Comment by CzBiX** [comment]
duplicate to #57
