### ISSUE TITLE
请教一个问题，qbitTorrent webui 选项中没有替换 ui 的选项

### ISSUE THREAD

**Issue by RikkaBlue** [CzBiX/qb-web#5]
因为是一个没有显示器的服务器，只能用 qbitTorrent-nox ，但是并没有在 选项-webui 中找到替换 ui 的地方。
网上也没有找到信息。
![image](https://user-images.githubusercontent.com/46104879/71570333-9571fa00-2b0f-11ea-8eb3-852d17802a35.png)
```shell
$ qbittorrent-nox -v
qBittorrent v3.3.7
```

**Comment by CzBiX** [comment]
https://github.com/qbittorrent/qBittorrent/wiki/Alternate-WebUI-usage
