### ISSUE TITLE
请问如何在脚本中修改RSS的如下功能

### ISSUE THREAD

**Issue by yygd2008** [CzBiX/qb-web#55]
感谢大神制作WEBUI实现Qbittorrent内部RSS功能！
请问如何在脚本中修改RSS的如下筛选条件：
1.自动刷新时间
2.最大文件大小/最小文件大小
3.折扣信息discount（FREE/2*FREE/50%/30%）
4.最大RSS数量

THX～

**Comment by CzBiX** [comment]
不解答 QB 使用问题方面的问题
