### ISSUE TITLE
Settings UI

### ISSUE THREAD

**Issue by zlr1** [CzBiX/qb-web#6]
UI点击设置后报错TODO无法打开，大佬麻烦指点一下
![报错](https://user-images.githubusercontent.com/32821016/75689649-7a249600-5cdc-11ea-9f22-7dbbe76e0e9a.jpg)
![webui日志](https://user-images.githubusercontent.com/32821016/75689661-801a7700-5cdc-11ea-8881-67fd1293feb9.jpg)
![webui日志](https://user-images.githubusercontent.com/32821016/75689665-83adfe00-5cdc-11ea-9e6a-0ada4d0f78c7.jpg)

**Comment by CzBiX** [comment]
暂未实现设置功能。

**Comment by R-L-T-Y** [comment]
最新版本里切换旧版UI的按钮消失了

**Comment by CzBiX** [comment]
已实现部分设置
