### ISSUE TITLE
nginx config of "wiki:multi WebUI at the same time" not work

### ISSUE THREAD

**Issue by Casxt** [CzBiX/qb-web#69]
config in this [page](https://github.com/CzBiX/qb-web/wiki/Use-Nginx-to-running-multi-WebUI-at-the-same-time) not work

the location  part `location /api` should be `location /api/`
```
    location /api/ {
        proxy_pass              http://127.0.0.1:8080;
        proxy_http_version      1.1; 
    }

    location / {
        root /home/qbtuser/dist/public;
    }
```

**Comment by CzBiX** [comment]
Thanks,
it should be `location /api/`, but `location /api` also works.
Updated.
