### ISSUE TITLE
rss can't auto refresh and auto download

### ISSUE THREAD

**Issue by ceozero** [CzBiX/qb-web#70]
rss can't auto refresh and auto download

Settings cannot be saved.

**Comment by CzBiX** [comment]
It's a UI issue, settings actually saved.
We may resolve it in the coming Settings UI.

**Comment by Argon-D** [comment]
Hi guys , I have the same issue. I've set rss feed but even if auto-refresh and auto-download are on nothing happen :(.
Can you add also the timer or refresh? 30sec, 1minute,2minutes (for example)?
Any ETA of the new version with this fix? 
Thaanks !! :>
