### ISSUE TITLE
Setting categories not working if the category contains spaces

### ISSUE THREAD

**Issue by wieluk** [CzBiX/qb-web#74]
It is just loading forever I wanted to set categories for 98 Torrents but it didn't work so I tried one also didn't work. It just loads forever

**Comment by wieluk** [comment]
i tried a little bit arround and it is only not working if the category name has a space in it :)

**Comment by bbogdanov** [comment]
Hi @wieluk!

Can you be more specific where the setting category isn't working? Please provide steps to reproduce

**Comment by wieluk** [comment]
If you select multiple torrents and select "set category" in the top bar. But it is only not working when the name of category choosen contains one or multiple spaces in its name. For me i fixed it by changing the category name to "example_example". instead of "example example"

**Comment by CzBiX** [comment]
Can't reproduce.
