### ISSUE TITLE
在Torrent任务选择性下载文件选中的文件会自动消除选择一次

### ISSUE THREAD

**Issue by smdx** [CzBiX/qb-web#78]
你好，报个问题。在Torrent任务选择性下载文件选中的文件会自动消除选择一次，需要重新选择。

![Video_20201117122933](https://user-images.githubusercontent.com/9279217/99347127-3b1d8b80-28d1-11eb-85a5-a842d7cfa93b.gif)

**Comment by CzBiX** [comment]
使用最新版本 qb-web。

**Comment by smdx** [comment]
> 使用最新版本 qb-web。

使用的就是最新版本啊，qb-web-nightly-20201023

**Comment by smdx** [comment]
qBittorrent_Enhanced_Edition_v4.2.5.16 + qb-web-nightly-20201023

**Comment by CzBiX** [comment]
状态刷新不是实时的，可以操作以后等待几秒再看看

**Comment by smdx** [comment]
不是状态刷新的原因，我观察过了的确是取消了选择，而且像截图那样点击全选或者全部取消然后再点列表中的选项
一会都会变成反向选择。

**Comment by CzBiX** [comment]
我重复一遍，

> 状态刷新不是实时的，可以操作以后等待几秒再看看

另外我在 62991d4ee23cd6f6567ffd06ecc84f2160ace002 中加入了请求状态，一定程度上可以缓解这个问题。
