### ISSUE TITLE
Fix adding a category to torrents

### ISSUE THREAD

**Issue by BlazeBlaster** [CzBiX/qb-web#79]
Currently manually typing a category for torrents is broken, it doesn't auto set the correct download path.

**Comment by bbogdanov** [comment]
I use this feature regularly and it works fine. Please provide steps to reproduce

**Comment by BlazeBlaster** [comment]
This is all done with "Automatic Torrent Management" enabled.

So the first step is to either paste a magnet link in, or upload a torrent file, then manually type in the category. In the example below I've used "Test"

![Screenshot 2020-11-22 012508](https://user-images.githubusercontent.com/17521301/99899984-0d826a80-2c62-11eb-900d-c054170cfd3c.png)
![Screenshot 2020-11-22 012608](https://user-images.githubusercontent.com/17521301/99899992-2559ee80-2c62-11eb-9a54-b28b58203d3a.png)


As you can see, the saved folder should be "/Downloads/Test", but it is just "/Downloads"

![Screenshot 2020-11-22 012649](https://user-images.githubusercontent.com/17521301/99899999-3440a100-2c62-11eb-9379-01a6f0a950fb.png)

If I use one of the pre-made categories from the old web-ui, the location is set correctly.

![Capture](https://user-images.githubusercontent.com/17521301/99900044-96010b00-2c62-11eb-9609-d558c213c312.PNG)

Am I missing a step? It seems as though the editing of the category does not update the download path correctly
