### ISSUE TITLE
Manual tracker list lost when switching between custom WebUI and default WebUI

### ISSUE THREAD

**Issue by R-L-T-Y** [CzBiX/qb-web#8]

**Comment by R-L-T-Y** [comment]
最近版本依然复现。qbittorrent-nox 4.2.1。
在默认webui下填写自动加入的tracker, 确认后生效。
切换到qb-web后，一旦切换会默认webui，之前填写的tracker栏会被清空。

（最新版本信息按键好像失效了）

暂不确定是不是上游的问题

**Comment by CzBiX** [comment]
种子信息功能已经修复。
tracker 的问题无法复现。

**Comment by CzBiX** [comment]
上游的问题
https://github.com/qbittorrent/qBittorrent/pull/13587
