### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by bpvarsity** [CzBiX/qb-web#82]
Trying to build this from source and hit a snag. 
sudo yarn run build
yarn run v1.22.5
$ vue-cli-service build
 ERROR  Error: Cannot find module '@vue/cli-plugin-babel/preset' 

Any suggestions would be appreciated

**Comment by bbogdanov** [comment]
Did you run 'yarn'? Dumb question but possible situation

**Comment by CzBiX** [comment]
Please see [DEV.md](https://github.com/CzBiX/qb-web/blob/master/DEV.md).
No sudo required, and remember to do `yarn install` at first.
