### ISSUE TITLE
[BUG] Search field query persists across page refreshes

### ISSUE THREAD

**Issue by agneevX** [CzBiX/qb-web#84]
#### Describe the bug
Search query does not reset/get removed when the page is refreshed.

#### How to reproduce

1.  Type search query in search bar
2. Refresh page

#### Expected behavior
Text in search bar is removed once the page is refreshed.

#### Official behavior
N/A

#### Versions
- qBittorrent: N/A
- qb-web: dev

#### Additional notes

N/A

**Comment by CzBiX** [comment]
It's not a bug, but it can be improved.

**Comment by agneevX** [comment]
That's the only category of Issues :(
