### ISSUE TITLE
[Feature Request] Add Tagging

### ISSUE THREAD

**Issue by brettpetch** [CzBiX/qb-web#86]
This functionality is in the original UI, and is quite nice for those of us that script everything. We use it to track each tracker, as well as track when torrents were added to the client. If this functionality could be added to the qb-web ui it would be greatly appreciated.

![image](https://user-images.githubusercontent.com/38706195/103156963-5c994f00-477c-11eb-81fb-ad1bef3b45cd.png)
![image](https://user-images.githubusercontent.com/38706195/103156970-6e7af200-477c-11eb-825c-b5ccf93d8024.png)

cheers!
b

**Comment by CzBiX** [comment]
duplicate, #14
