### ISSUE TITLE
[BUG]magnet链接跳转错误

### ISSUE THREAD

**Issue by SINC-G** [CzBiX/qb-web#87]
## Describe the bug

点击磁链, 会跳转到 https://czbix.github.io/ 
而只有https://czbix.github.io/qb-web/#download=  这个页面才会处理磁链

## Versions

- qBittorrent: 4.3.2
- qb-web: [e.g. 20201023]

**Comment by slikie** [comment]
bump, this is broken on proxied /api/* method too
