### ISSUE TITLE
webui的性能问题

### ISSUE THREAD

**Issue by zhufeng** [CzBiX/qb-web#88]
我尝试过官方webui以及qb-web的webui，官方内置的webui还好，在种子小于1000的情况下，客户端浏览器吃内存和cpu的情况还能接受。

qb-web在有几百个种子的情况下，客户端的浏览器单个chrome.exe能占到超过2GB。

不知这种情况下要如何排查问题？

**Comment by CzBiX** [comment]
为了实现简单，每次更新数据都会 cloneDeep 所有数据。可能是这里导致的性能问题。
https://github.com/CzBiX/qb-web/blob/67f86700151e096c51bbec7bcf62254f636c08e3/src/store/index.ts#L42

**Comment by eazydripz** [comment]
Thank you.

**Comment by ipcjs** [comment]
。。。确实好卡，尤其是再手机上
