### ISSUE TITLE
[BUG] Progress bar text visual issue

### ISSUE THREAD

**Issue by agneevX** [CzBiX/qb-web#90]
## Describe the bug

<img width="300" alt="image" src="https://user-images.githubusercontent.com/19761269/104321532-c00bd680-5509-11eb-9b3a-07ff9421cdcf.png">

## Versions

- qBittorrent: N/A
- qb-web: `master`

## Additional notes
N/A

**Comment by CzBiX** [comment]
duplicate of #45
