### ISSUE TITLE
[BUG] Blank page on webOS browser

### ISSUE THREAD

**Issue by qarkai** [CzBiX/qb-web#91]
## Describe the bug

Blank page on webOS browser. It's kind of really old version (~54) of Chromium.

## How to reproduce

Open Web UI address on webOS browser.

## Expected behavior

Web UI is usable.

## Official behavior

Official Web UI works like a charm.

## Versions

- qBittorrent: 4.3.1
- qb-web: 20201023

**Comment by angristan** [comment]
Did you use a release? https://github.com/CzBiX/qb-web/releases

**Comment by qarkai** [comment]
@angristan Yep, it's in the bug description.

**Comment by CzBiX** [comment]
it may caused by incorrectly configuration, can you confirm it works in the modern browser?

**Comment by wallheater** [comment]
Same issue for me on older qBittorrent 4.1.9.1.
Tried browsers Chrome 87.0.4280.141 (Official Build) (64-bit) and Firefox 84.0.2 (64-bit).
Tried the 20201023 release and cloned master.
Execution log of qBittorrent includes this warning: "Couldn't load Web UI translation for selected locale (en)."

**Comment by qarkai** [comment]
@CzBiX Yes, works in Chromium 87+, Firefox 84.

**Comment by wallheater** [comment]
Does it maybe require a newer version of qBittorrent? Or is there some configuration required that is not written in INSTALL.md?

**Comment by wallheater** [comment]
Issue persists after upgrading to qBittorrent **4.3.3**.

Examining "blank page" source shows it is the exact contents of **public/index.html**. So maybe the _"built files will be auto injected"_ is not happening.

**Comment by wallheater** [comment]
Here's what got it working for me:
```
$ sudo apt install npm
$ cd ~/src/qbittorrent-alt-web-ui
$ npm install
$ npm run build
```
This creates `dist` directory containing its own `public/index.html`.

Then in qBittorrent preferences, change **Files location** to `~/src/qbittorrent-alt-web-ui/dist`.

**Comment by qarkai** [comment]
@wallheater So you use source (`git clone https://github.com/CzBiX/qb-web.git`), not release from https://github.com/CzBiX/qb-web/releases/latest?

**Comment by wallheater** [comment]
I started with the release (20201023) but the zip archive did not include `dist/`. So then I did `git clone` and tried that.

_Now_, feeling stupid, I just downloaded the [release zip](https://github.com/CzBiX/qb-web/releases/download/nightly-20201023/qb-web-nightly-20201023.zip) again, and it _does_ include `dist/` and it works. :dizzy_face: 

But I found the original `qb-web-nightly-20201023.zip` file which I got on 2021-Jan-21 and it definitely does not include `dist/`. Maybe I got the zip by starting [here](https://github.com/CzBiX/qb-web/tree/nightly-20201023) instead? It gives the same archive name.

Anyway, seems like this is **not a bug**. Possible user error. 

:arrow_right: Make sure you download the **zip file** from the **Assets** on the [release page](https://github.com/CzBiX/qb-web/releases/latest). The archive will contain just the `dist/` folder at the root level.

**Comment by qarkai** [comment]
@wallheater, your case is unrelated to this bug. I definitely use nightly release and it works on modern browsers (even mobile versions) but doesn't work on webOS browser.

**Comment by CzBiX** [comment]
What's the webOS version you using?
What's the error in browser console?

**Comment by qarkai** [comment]
webOS 4.3.0-9703. I don't have access to browser console. BTW it's Chromium 53: https://webostv.developer.lge.com/discover/specifications/web-engine/

**Comment by qarkai** [comment]
I have opened page in Opera 40. It's based on Chromium 53 so errors should be the same. Error is `Uncaught SyntaxError: Unexpected token ...` in VAlert.js:116.

**Comment by CzBiX** [comment]
@qarkai Could you try this [webos](https://github.com/CzBiX/qb-web/tree/webos) branch, see if it works.

**Comment by qarkai** [comment]
@CzBiX Do I have to run `npm install/run`?

**Comment by CzBiX** [comment]
`yarn install` then `yarn build`.
Use files in `dist` dir.

See [DEV.md](https://github.com/CzBiX/qb-web/blob/master/DEV.md).

**Comment by qarkai** [comment]
No, that didn't help. Error is the same: `Uncaught SyntaxError: Unexpected token ...` but now in VExpansionPanels.js:31.
Also there is referrer policy error: `Failed to set referrer policy: The value 'same-origin' is not one of 'always', 'default', 'never', 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-crossorigin', or 'unsafe-url'. The referrer policy has been left unchanged.`

**Comment by CzBiX** [comment]
that's it.
this version is too old, and there is no easy way to support it.
I can't fix it, sorry.
