### ISSUE TITLE
[BUG]不可接受的文件类型，只允许使用常规文件。

### ISSUE THREAD

**Issue by Gaojianli** [CzBiX/qb-web#98]
## Describe the bug

Just set the alternate WebUI, using behind a nginx reserve proxy
![image](https://user-images.githubusercontent.com/19235246/112023790-8a6d1480-8b6e-11eb-86aa-86929536b522.png)

## How to reproduce

1.  Set like this
 
![image](https://user-images.githubusercontent.com/19235246/112024113-d455fa80-8b6e-11eb-91ed-618d062038d2.png)

2.  Visit https://myserver/qbt

## Expected behavior

Show this web ui

## Official behavior

Show default ui

## Versions

- qBittorrent: 4.3.3
- qb-web: nightly-20210315

## Additional notes
Here is the path config and permission config
_Add any other notes about the problem here._
![image](https://user-images.githubusercontent.com/19235246/112024336-0e270100-8b6f-11eb-9c76-9ce5cff3dd3a.png)

**Comment by CzBiX** [comment]
解压后保留 public 目录
